include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    sort_pub_dependencies: true
    recursive_getters: true
    prefer_single_quotes: true
    unnecessary_this: true
